name: atticcleaning-website
region: nyc
domains:
  - domain: atticcleaning.com
    type: PRIMARY
    zone: atticcleaning.com

static_sites:
  - name: atticcleaning-static
    source_dir: /
    index_document: index.html
    error_document: 404.html
    
    # GitHub repository connection
    github:
      repo: atticcleaning/atticcleaning-directory
      branch: main
      deploy_on_push: true
    
    # Build settings (none needed for pure static)
    build_command: ""
    
    # Environment
    environment_slug: node-js
    
    # Routes
    routes:
      - path: /

# CDN and performance settings handled by DigitalOcean Spaces